server {
    listen 80;

    location /api/monitoring/ {
        proxy_pass http://observability-service:4001/api/;
    }

    location /api/ {
        proxy_pass http://main-service:3001/api/;
    }

    location / {
        proxy_pass http://web-client:80;
    }
}
